version: '3.9'
services:
    web-dev:
        build: 
            context: .
            target: development
        ports:
            - "4000:5000"
        volumes:
            - ./app:/app/app
        environment: 
            PORT: 4000
            FLASK_DEBUG: 1

    web-production:
        build: 
            context: .
            target: production
        ports:
            - "4000:5000"
        volumes:
            - ./app:/app/app
        environment: 
            PORT: 4000
            FLASK_DEBUG: 1  