version: '3.9'
services:
    web-development:
        container_name: development
        build:
            dockerfile: Dockerfile 
            context: .
            target: development
        ports:
            - 4000:5000
        volumes:
            - type: bind
              source: ./app
              target: /app/app
        environment:
            PORT: 4000 
            FLASK_DEBUG: 1

    web-production:
        container_name: production
        build: 
            dockerfile: Dockerfile
            context: .
            target: production
        ports:
            - 5000:5000
        volumes:
            - type: bind
              source: ./app
              target: /app/app
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1