name: Continuous Integration
on: push

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
with:
   args: --sarif-file-output=snyk.sarif

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: starting
        channel: ‘#slack-notifications’
        message: 'GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}'
      if: always()

    - name: Initating Security Scan
      uses: snyk/actions/python-3.8@master

    - name: Uploading result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif