name: Continuous Integration
on: push

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Scanning Python code for vulnerabilities
      uses: snyk/actions/python@master
      with:
        command: monitor

    - name: Buidling Docker Image
      run: docker build --target development --tag microblog:development .

    - name: Scanning Docker Image for vulnerabilities
      uses: snyk/actions/docker@master
      continue-on-error: true
      with:
        image: microblog:development
        args: --file=Dockerfile,--severity-threshold=high

              
    - name: Slack Notification
      uses: act10ns/slack@v1
      with:
        status: starting
        channel: ‘#slack-notifications’
        message: 'GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}'
      if: always()